### ISSUE TITLE
Jedi crashing on Windows 8.1 x64

### ISSUE THREAD

**Issue by MetaEntity** [jazzscheme/jedi-windows#1]
Hello,

I am trying to run jedi on Windows 8.1 x64.
The IDE starts and freeze after about 5 seconds.
If I attach a Visual Studio to the process it appears that memory read/write violation occured:

![jedi-debugger](https://cloud.githubusercontent.com/assets/8394023/3855666/a14265ec-1ee8-11e4-92f1-16d6bd936dd4.png)

I tried to compile the IDE from the source, but the result is exactly the same.

Console applications works well (Gambit, Jazz ...).
I then tried to run the sample game gomoku, I get a crash too at some point, like if it was related to some UI code.

I am looking forward using this project which seems great, let me inform I you need more information for the debug.

Thanks,

Dorian

**Comment by MetaEntity** [comment]
Same problem on Windows Server 2012R2, while it works well on Windows 7 and Windows Server 2008R2.

**Comment by gcartier** [comment]
Wow great investigative work. I am going on vacation for about 1 month 1/2 but I will look into it when I return (good idea to use Visual Studio to attach to the process), but in the meantime you can use the following quick hack I added to Jazz a couple months ago that fixes the problem:

In your Jazz global configuration file that should be located at ~/.jazz/2.5.3/.jazzini insert the following line:

(define use-ste? #t)

The variable stands for use-single-threaded-events? Jazz now uses multiple Gambit threads to handle events but somehow this causes problems under Windows 8.1 that I didn't have time yet to investigate.

**Comment by MetaEntity** [comment]
Thanks for the trick, it works.
Could you tell me where to find a documentation about Jazz and the Jedi IDE as well as the libraries available. I would like to try building an OpenGL with it.

Thanks in advance,

Bonnes vacances :)

**Comment by jazzscheme** [comment]
Removed the use-ste? as it seems it is not needed anymore for later versions of Windows 8.1. This was probably some Windows change that was not backward-compatible that they just fixed.
